<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_FINAL_APPROVED</name>
   <tag></tag>
   <elementGuidId>cb1ceefe-d35f-4579-9c75-df0743272873</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.mat-cell.cdk-cell.cdk-column-applicationStatusStr.mat-column-applicationStatusStr.ng-star-inserted > div.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/app-home/mat-sidenav-container/mat-sidenav-content/div/div[2]/app-credit-assessment-processing/mat-drawer-container/mat-drawer-content/mat-drawer-container/mat-drawer-content/mat-tab-group/div/mat-tab-body[1]/div/div/div[3]/app-credit-assessment-processing-data-table/div/div[1]/table/tbody/tr/td[11]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2db657c2-07b3-45a2-83fb-352d6fd2b761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>ec6aa5fd-f7dd-42d1-9777-775e8be60597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>APPROVED</value>
      <webElementGuid>245c0730-2251-432a-836d-8848757e190b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-6-0&quot;)/div[@class=&quot;mat-tab-body-content ng-tns-c206-179 ng-trigger ng-trigger-translateTab&quot;]/div[@class=&quot;whiteframe-01 ng-star-inserted&quot;]/div[3]/app-credit-assessment-processing-data-table[1]/div[@class=&quot;stroked-top ng-star-inserted&quot;]/div[@class=&quot;overflow-auto ng-star-inserted&quot;]/table[@class=&quot;mat-table cdk-table mat-sort fixed-column-width margin-t-1&quot;]/tbody[1]/tr[@class=&quot;mat-row cdk-row ng-star-inserted&quot;]/td[@class=&quot;mat-cell cdk-cell cdk-column-applicationStatusStr mat-column-applicationStatusStr ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>fb285e8b-a9d5-4b08-ba2e-8334d04f9649</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-6-0']/div/div/div[3]/app-credit-assessment-processing-data-table/div/div/table/tbody/tr/td[10]/div</value>
      <webElementGuid>0b993ab5-b440-4b9b-8071-54b33db71e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BENQ'])[1]/following::div[1]</value>
      <webElementGuid>d2db1809-4918-4bfe-b115-11b7ca43b520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Máy tính để bàn'])[1]/following::div[2]</value>
      <webElementGuid>f6767bf5-b160-4e77-b458-480896ba3f4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FINAL SETTLED'])[1]/preceding::div[1]</value>
      <webElementGuid>a5b244c2-6c92-4399-9f6d-0372399e0e74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APPROVED'])[2]/preceding::div[2]</value>
      <webElementGuid>e06fdb38-5be1-4b6c-a8cd-f00a9a0f3371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]/div</value>
      <webElementGuid>8007aee1-175e-4d5d-b06c-a7a12f5650c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'APPROVED' or . = 'APPROVED')]</value>
      <webElementGuid>a34a2cda-3348-4df7-beae-356ef00e6e33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
