<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_IDCard</name>
   <tag></tag>
   <elementGuidId>fd803d22-5f30-4cc4-a4c4-5fc0413e6458</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.mat-cell.cdk-cell.cdk-column-applicationStatusStr.mat-column-applicationStatusStr.ng-star-inserted > div.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/app-home/mat-sidenav-container/mat-sidenav-content/div/div[2]/app-credit-assessment-processing/mat-drawer-container/mat-drawer-content/mat-drawer-container/mat-drawer-content/mat-tab-group/div/mat-tab-body[1]/div/div/div[3]/app-credit-assessment-processing-data-table/div/div[1]/table/tbody/tr/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f2e17029-ac9b-49e7-9c46-1227ecc2b211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>a4babb4f-17e2-4d9d-9b2a-d3e073e903d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>APPROVED</value>
      <webElementGuid>575b229f-4d92-4467-9c40-d7c508c055df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-6-0&quot;)/div[@class=&quot;mat-tab-body-content ng-tns-c206-179 ng-trigger ng-trigger-translateTab&quot;]/div[@class=&quot;whiteframe-01 ng-star-inserted&quot;]/div[3]/app-credit-assessment-processing-data-table[1]/div[@class=&quot;stroked-top ng-star-inserted&quot;]/div[@class=&quot;overflow-auto ng-star-inserted&quot;]/table[@class=&quot;mat-table cdk-table mat-sort fixed-column-width margin-t-1&quot;]/tbody[1]/tr[@class=&quot;mat-row cdk-row ng-star-inserted&quot;]/td[@class=&quot;mat-cell cdk-cell cdk-column-applicationStatusStr mat-column-applicationStatusStr ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>bdd8d10f-00e8-4524-9021-e6068aa97af4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-6-0']/div/div/div[3]/app-credit-assessment-processing-data-table/div/div/table/tbody/tr/td[10]/div</value>
      <webElementGuid>e2660295-3109-4ac3-9231-84d15c399126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BENQ'])[1]/following::div[1]</value>
      <webElementGuid>6332c864-675e-479f-a19f-d74457c79aea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Máy tính để bàn'])[1]/following::div[2]</value>
      <webElementGuid>0f1c83c7-5c13-4394-8ff4-3785aa6ae483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FINAL SETTLED'])[1]/preceding::div[1]</value>
      <webElementGuid>e6f82142-6be1-46f6-bfbf-404018188482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APPROVED'])[2]/preceding::div[2]</value>
      <webElementGuid>89b97aee-679f-4d88-b2dd-2cc2016f4839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]/div</value>
      <webElementGuid>f80c0c27-e3d5-4d4f-bc88-b045305c0eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'APPROVED' or . = 'APPROVED')]</value>
      <webElementGuid>81a67524-9e1d-4fc7-85df-aa3ac23cc000</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
