<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Dashboard</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>726618f9-465b-4c43-a2fb-30582abbb693</testSuiteGuid>
   <testCaseLink>
      <guid>556f9c92-370c-4396-9f28-ce7b66ec3ae1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>38f5ff2a-4e2a-4b53-825b-17970cfeb3e4</id>
         <masked>false</masked>
         <name>ProfileNo</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/API - Payoo/AddProfile</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>85401ef8-237a-46ce-a6fc-c358aace33e3</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value>1-2</value>
         </iterationEntity>
         <testDataId>Data Files/Applications</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>85401ef8-237a-46ce-a6fc-c358aace33e3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ProfileNo</value>
         <variableId>38f5ff2a-4e2a-4b53-825b-17970cfeb3e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>85401ef8-237a-46ce-a6fc-c358aace33e3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FullName</value>
         <variableId>5fd12f0e-9f27-46dc-98c7-5842df5473d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>85401ef8-237a-46ce-a6fc-c358aace33e3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>CusNameEng</value>
         <variableId>fa3bb54d-4d78-4cc7-badd-9e3f83e05163</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>85401ef8-237a-46ce-a6fc-c358aace33e3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>IDCard</value>
         <variableId>ac202a55-a538-48be-9a03-bc000cabcb46</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3d3755b1-575d-4828-8194-eac36b85152c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Web Credentials/URL</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>68865d06-25be-4c6e-a7e9-1d8d6820878d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Credential</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>68865d06-25be-4c6e-a7e9-1d8d6820878d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>URL</value>
         <variableId>590bde64-f2f9-4343-89fc-40ac9bb0c5ce</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aa1a74c8-7d3e-4336-9884-ffa37f4a3e9c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Web Credentials/Log In</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ca3d02b2-f471-4f23-be32-92c348182359</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Credential</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>ca3d02b2-f471-4f23-be32-92c348182359</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>8aead738-00a7-4805-af9a-836c46b5eed6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ca3d02b2-f471-4f23-be32-92c348182359</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>38e83f34-2641-40e4-b124-9a49d1649e18</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f6a9c423-010e-4fde-9408-0b598eae0bc4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Credit Assessment/Dashboard/Navigate_Dashboard</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>8e9ea943-0e25-413a-94a6-67c68fc7cc1c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Credit Assessment/Dashboard/Create Application</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>036a0b4c-fc80-44a5-b52a-fa4a952dcab0</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value>25-50</value>
         </iterationEntity>
         <testDataId>Data Files/Applications</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>036a0b4c-fc80-44a5-b52a-fa4a952dcab0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ProfileNo</value>
         <variableId>92b93d19-0b6a-4e3f-997e-886dfeb5b081</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>faa0b89a-d39d-4201-9830-b132b4d2b34c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Credit Assessment/Processing/Navigate_Processing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>6130ff2a-68d6-4a52-89ef-5b7bff17e7c0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Credit Assessment/Processing/Verify_Application_Status</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>7b3eb1d9-9c9a-4a0d-810d-017d3e9717f7</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Applications</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>7b3eb1d9-9c9a-4a0d-810d-017d3e9717f7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ProfileNo</value>
         <variableId>1dfef550-f1b5-4fd5-b2c3-6f705db1962e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7b3eb1d9-9c9a-4a0d-810d-017d3e9717f7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ApplicationStatus</value>
         <variableId>972d9b9e-3a12-4704-bf32-d8229cde1089</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7b3eb1d9-9c9a-4a0d-810d-017d3e9717f7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>IDCard</value>
         <variableId>38d33114-ac59-4fb6-b2f5-85824cb85b5d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>20fcc7f2-6e17-4e72-bb3f-15c49c8364cd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Web Credentials/Log Out</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
