<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Agreement Date_mat-input-35</name>
   <tag></tag>
   <elementGuidId>e40eece4-d1ab-47ae-afae-647ded6f0e61</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-input-35</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;mat-input-35&quot;)[count(. | //input[@formcontrolname = 'settlementDate' and @class = 'mat-input-element mat-form-field-autofill-control ng-tns-c156-58 ng-invalid cdk-text-field-autofill-monitored ng-touched ng-dirty' and @id = 'mat-input-35' and @aria-invalid = 'true' and @aria-required = 'true' and @aria-haspopup = 'dialog' and @aria-describedby = 'mat-error-2']) = count(//input[@formcontrolname = 'settlementDate' and @class = 'mat-input-element mat-form-field-autofill-control ng-tns-c156-58 ng-invalid cdk-text-field-autofill-monitored ng-touched ng-dirty' and @id = 'mat-input-35' and @aria-invalid = 'true' and @aria-required = 'true' and @aria-haspopup = 'dialog' and @aria-describedby = 'mat-error-2'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@formcontrolname=&quot;settlementDate&quot;]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f71ef370-2c31-4ee1-a3fe-f6ae2a41eeb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>settlementDate</value>
      <webElementGuid>ade98d3b-bf1e-4b00-950e-4007e04cb1a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c156-58 ng-invalid cdk-text-field-autofill-monitored ng-touched ng-dirty</value>
      <webElementGuid>3cff1899-4b12-4bb4-9fe5-aafc294e406e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-input-35</value>
      <webElementGuid>2de8c983-4fa6-4adf-aa58-d21316bc5572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b8a918c1-d1cc-4bd6-b0fb-55f7b66f4590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1cd49f4e-6498-4255-bf17-b29b3cd213e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>9d8985be-a265-4639-a05d-a3f2cfa8bde9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>mat-error-2</value>
      <webElementGuid>3481440d-75c9-4f8f-a265-b1418635ce24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-input-35&quot;)</value>
      <webElementGuid>3f01852e-fbe9-4ca9-bd48-c0fbf3bd3579</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-input-35']</value>
      <webElementGuid>39aab0e1-edd7-4d46-837c-0185aed80e21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-2-0']/div/mat-card/form/div/p[2]/mat-form-field/div/div/div[3]/input</value>
      <webElementGuid>006976a8-624d-4a5a-b3e0-e628edce5487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/mat-form-field/div/div/div[3]/input</value>
      <webElementGuid>42653ae4-9a11-4a4d-be3a-b88f5bbb86e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mat-input-35']</value>
      <webElementGuid>9ab85f96-482a-48a9-ab07-55cea799e3d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
