<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Settlement Registration (Staff)_mat-input-2</name>
   <tag></tag>
   <elementGuidId>ca80012b-8e51-4651-9f7a-835054c7b1ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-input-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/app-home/mat-sidenav-container/mat-sidenav-content/div/div[1]/app-main-toolbar/mat-toolbar/app-search-bar/form/mat-form-field/div/div[1]/div[3]/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;mat-input-2&quot;)[count(. | //input[@formcontrolname = 'value' and @autocomplete = 'off' and @class = 'mat-input-element mat-form-field-autofill-control ng-tns-c156-9 ng-untouched ng-pristine ng-valid cdk-text-field-autofill-monitored' and @id = 'mat-input-2' and @placeholder = 'Agreement Number' and @aria-invalid = 'false' and @aria-required = 'false']) = count(//input[@formcontrolname = 'value' and @autocomplete = 'off' and @class = 'mat-input-element mat-form-field-autofill-control ng-tns-c156-9 ng-untouched ng-pristine ng-valid cdk-text-field-autofill-monitored' and @id = 'mat-input-2' and @placeholder = 'Agreement Number' and @aria-invalid = 'false' and @aria-required = 'false'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9bad08f7-76ce-4ba8-a3de-1f4b23a68fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>eeb148e1-55c8-4391-8b37-0972adc7d2ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>203cbe56-f9b2-4444-acfb-671b395fca64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c156-9 ng-untouched ng-pristine ng-valid cdk-text-field-autofill-monitored</value>
      <webElementGuid>fddb6ebc-deed-4cd3-9baa-c47533cf9563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-input-2</value>
      <webElementGuid>febea80c-1c91-4423-b721-60402bcf6003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Agreement Number</value>
      <webElementGuid>b7a273bc-198b-4deb-8cc0-54eac3a7c514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e778762e-7e35-4b05-add2-06ffb0ed2501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>06ba7e8d-b855-4fb2-96f2-e47a085ff956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-input-2&quot;)</value>
      <webElementGuid>cd273ecc-6a68-4b0d-81f9-f71d13c18c90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-input-2']</value>
      <webElementGuid>bef9a2c0-4b52-4ca6-9ae0-b079380088ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6feac9de-ca3a-48af-a103-4c0d9c92aec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mat-input-2' and @placeholder = 'Agreement Number']</value>
      <webElementGuid>b69ff8c5-3651-4119-8916-d0b4f82af58b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
