<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Waiting</name>
   <tag></tag>
   <elementGuidId>4f9f53bb-604e-4d14-a6d5-7311d1c52096</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-tab-label-2-0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;mat-tab-label-2-0&quot;)[count(. | //div[@role = 'tab' and @class = 'mat-ripple mat-tab-label mat-focus-indicator mat-tab-label-active ng-star-inserted cdk-focused cdk-mouse-focused' and @id = 'mat-tab-label-2-0' and @tabindex = '0' and @aria-posinset = '1' and @aria-setsize = '3' and @aria-controls = 'mat-tab-content-2-0' and @aria-selected = 'true' and @aria-disabled = 'false' and (text() = '  Waiting' or . = '  Waiting')]) = count(//div[@role = 'tab' and @class = 'mat-ripple mat-tab-label mat-focus-indicator mat-tab-label-active ng-star-inserted cdk-focused cdk-mouse-focused' and @id = 'mat-tab-label-2-0' and @tabindex = '0' and @aria-posinset = '1' and @aria-setsize = '3' and @aria-controls = 'mat-tab-content-2-0' and @aria-selected = 'true' and @aria-disabled = 'false' and (text() = '  Waiting' or . = '  Waiting')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/app-home/mat-sidenav-container/mat-sidenav-content/div/div[2]/app-credit-assessment-dashboard/mat-drawer-container/mat-drawer-content/mat-drawer-container/mat-drawer-content/mat-tab-group/div/mat-tab-body[1]/div/div/div[3]/mat-tab-group/mat-tab-header/div[2]/div/div/div[2]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ad4fcb98-7444-46fd-8649-41085a0a8b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>2d12382c-5950-4c1c-be33-7b29ced2dfcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-ripple mat-tab-label mat-focus-indicator mat-tab-label-active ng-star-inserted cdk-focused cdk-mouse-focused</value>
      <webElementGuid>91f7c1a6-36ff-4750-b1dd-d20451ed17ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-tab-label-2-0</value>
      <webElementGuid>8cfac9e0-486a-40be-a7e0-a9f9ca0a4df4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d07d4228-253d-45c4-972f-0618f1b655b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-posinset</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6a8939be-c576-4c46-aebe-63cbfe80462e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-setsize</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>1c90fd90-f065-4588-b78c-77bc2d2fa8b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>mat-tab-content-2-0</value>
      <webElementGuid>841d71fc-1a56-453d-9448-36ca0f033118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f1ee343d-7f6a-4799-b605-eb3545b86021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7c476836-f4c5-4e6a-84a7-a5b0a1f9121a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Waiting</value>
      <webElementGuid>fe0021d1-6561-4b1c-a18a-2aafc48f59e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-label-2-0&quot;)</value>
      <webElementGuid>86e84e91-af56-4174-abab-73eca5c9107c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mat-tab-label-2-0']</value>
      <webElementGuid>ef2b5c74-3bd2-4268-88a9-df36cfaafd93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-1-0']/div/div/div[3]/mat-tab-group/mat-tab-header/div[2]/div/div/div</value>
      <webElementGuid>4aeb3be4-f38b-45d5-bdbf-841332ba1ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request Number'])[2]/following::div[32]</value>
      <webElementGuid>e348922c-457e-47fe-b3d1-68a7a258aebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Waiting'])[1]/following::div[56]</value>
      <webElementGuid>c0fd48ad-2a9f-412e-9867-4bef4f10f65e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Processing'])[2]/preceding::div[2]</value>
      <webElementGuid>c46f3a1d-c4b8-43aa-ae17-87ca926df5d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/mat-tab-group/mat-tab-header/div[2]/div/div/div</value>
      <webElementGuid>8554f589-cfd4-4813-a22c-4ffc20677208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mat-tab-label-2-0' and (text() = '  Waiting' or . = '  Waiting')]</value>
      <webElementGuid>5669faf6-3ce9-4014-94d2-d2933b642124</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
