<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_ID</name>
   <tag></tag>
   <elementGuidId>d5f67af7-0dfb-45cb-a1b5-11c53c06e4f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/mat-checkbox/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-checkbox-116 > label.mat-checkbox-layout</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>354aa73b-699f-4157-b13e-7bf94511804d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-checkbox-layout</value>
      <webElementGuid>6218c8f1-1a28-49e7-8587-61b0b0735cdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>mat-checkbox-116-input</value>
      <webElementGuid>e97cf6f9-40cc-4070-a119-db9d2683173a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  ID </value>
      <webElementGuid>d1b15f09-3397-4e1f-ba05-3c4e8c40e97b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-checkbox-116&quot;)/label[@class=&quot;mat-checkbox-layout&quot;]</value>
      <webElementGuid>fac9625b-5ec5-43db-907e-610732c6240e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-checkbox[@id='mat-checkbox-116']/label</value>
      <webElementGuid>8ad24a7f-bd3a-4d8c-8ce2-f080ac697697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remark To Judgement'])[1]/following::label[1]</value>
      <webElementGuid>e1b6669a-ca61-47c6-9aea-7858393e5a27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending'])[2]/following::label[2]</value>
      <webElementGuid>3030d641-2475-4a1a-8a80-98feb924ef7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/mat-checkbox/label</value>
      <webElementGuid>af41c014-f6b0-4298-a665-983838c234be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '  ID ' or . = '  ID ')]</value>
      <webElementGuid>8c897a06-ef4a-4deb-9a6a-b8cdc442171f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
