<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_APPROVE</name>
   <tag></tag>
   <elementGuidId>4aa73e27-6944-45ef-8098-bae38578d526</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[(text() = ' APPROVE' or . = ' APPROVE')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.mat-radio-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ba83c4df-c5dc-432e-8197-be8ccc3f1310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-radio-label</value>
      <webElementGuid>5299ae35-fe79-4496-be49-60bb563d8643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>mat-radio-4-input</value>
      <webElementGuid>64567f0d-4d05-4292-b084-1a20635a7259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> APPROVE</value>
      <webElementGuid>b05ad109-23f8-478d-a07b-458b23a49b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-radio-4&quot;)/label[@class=&quot;mat-radio-label&quot;]</value>
      <webElementGuid>5f013b8a-d450-4025-bd99-eff9b55639dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-radio-button[@id='mat-radio-4']/label</value>
      <webElementGuid>86b2bd30-14c8-4d02-990f-b3615af4651d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check List'])[1]/following::label[1]</value>
      <webElementGuid>3a1cf6a0-90d5-4ae9-b105-1834069646bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-radio-button/label</value>
      <webElementGuid>eaae1f65-22f8-4ea6-8304-a7bf784e9f54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = ' APPROVE' or . = ' APPROVE')]</value>
      <webElementGuid>d1a27ee2-4576-4c77-992d-1560ff77f17f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
