<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Clear All_mat-chip-list-input-1</name>
   <tag></tag>
   <elementGuidId>8ab8bab4-c1b8-4fac-a5b3-9da3a9d36a71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-chip-list-input-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/app-home/mat-sidenav-container/mat-sidenav-content/div/div[2]/app-final-settlement/mat-drawer-container/mat-drawer-content/mat-drawer-container/mat-drawer-content/div/div[2]/app-filter-chips/mat-form-field/div/div[1]/div[3]/mat-chip-list/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d48a1c4f-0c69-4202-bf1e-e7378b61e185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-chip-input mat-input-element</value>
      <webElementGuid>e4b93c48-eaa4-4989-abe9-aef1f8cffe0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-chip-list-input-1</value>
      <webElementGuid>9c26565f-8255-4963-9712-7c67d30cd5f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Filter Result</value>
      <webElementGuid>f8f36d7f-e4c2-48be-b0ce-341cc9d23604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-chip-list-input-1&quot;)</value>
      <webElementGuid>77c754d7-30d4-49d7-9972-e795ea680b98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-chip-list-input-1']</value>
      <webElementGuid>f27a0ac2-59a0-4baf-9b5e-185ef0adfc56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-chip-list[@id='mat-chip-list-1']/div/input</value>
      <webElementGuid>260264da-e877-4f8b-bad2-57c29f8f2a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-filter-chips/mat-form-field/div/div/div[3]/mat-chip-list/div/input</value>
      <webElementGuid>99a485ce-b50f-4e29-b1e5-1edaf2714363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mat-chip-list-input-1' and @placeholder = 'Filter Result']</value>
      <webElementGuid>7cbfd038-95a0-4711-abec-131fb6114f8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
